### ISSUE TITLE
Compilation on Windows

### ISSUE THREAD

**Issue by schneidermichal** [geonef/php5-gdal#5]
Hi,

I'm trying compile this extension on Windows, but I'm facing problem with an error:

ogrdatasource.cc(44) : error C2065: 'tsrm_ls' : undeclared identifier

The problem is on this function:
zend_hash_next_index_insert(&GDAL_G(ogrDataSources), &(obj->datasource), sizeof(obj->datasource), NULL)

I found this article: http://blog.golemon.com/2006/06/what-heck-is-tsrmlscc-anyway.html, but I still don't know how to fix it.

Thank you for advice.

**Comment by schneidermichal** [comment]
OK, I've resolved it, when I configured PHP with --disable-zts.

Now I can compile code, but I cannot link it. I think I don't have all dependencies. Do you now, which dependency is for GDALDriverManager::MoveDriver?

Thank a lot for advice.

**Comment by geonef** [comment]
Hi Schneidermichal,

Unfortunately I do not develop on Windows (but Linux) so I can't check out
what is the problem there.

If you can paste to me what error you get, I may guess about the
dependencies...

**Comment by schneidermichal** [comment]
Hi,

thank you very much for your time.

Here's my problem:

   Creating library Release\php5.lib and object Release\php5.exp
   Creating library Release\php_gdal.lib and object Release\php_gdal.exp
gdaldrivermanager.obj : error LNK2019: unresolved external symbol "public: void __thiscall GDALDriverManager::MoveDriver(class GDALDriver *,int)" (?MoveDriver@G
DALDriverManager@@QAEXPAVGDALDriver@@H@Z) referenced in function "void __cdecl zim_GDALDriverManager_MoveDriver(int,struct _zval_struct *,struct _zval_struct *
*,struct _zval_struct *,int)" (?zim_GDALDriverManager_MoveDriver@@YAXHPAU_zval_struct@@PAPAU1@0H@Z)
Release\php_gdal.dll : fatal error LNK1120: 1 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe"' : return code '0x2'

Again, thanks a lot!

**Comment by geonef** [comment]
Hi,

Do you actually need the GDALDriverManager::MoveDriver method?

I just checked http://www.gdal.org/classGDALDriverManager.html, there is no
doc and I can't see how it can be useful. My first concern was to check at
which version of GDAL the method appeared.

So... If you don't need it, just comment it out. And feel free to send a
pull request with your change as it may be useless at all.

**Comment by schneidermichal** [comment]
Hi,

I think I don't need it at all ;-) I comment it out and I can now compile it. Hooray :-)

![gdal](https://f.cloud.github.com/assets/2735984/1324166/2190fefe-34aa-11e3-83c6-0ed4ae1361e8.png)

Thank you very much!

I'll test it in PHP and if I didn't find any functionality I would send a pull request.
